# A small workflow to generate an exe

name: Windows CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ntbuild:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Install dependencies
        run: pip install questionary
      - name: Build exe
        run: python -m PyInstaller $GITHUB_WORKSPACE/cowserve.py -F --noupx -c
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
           name: cowserve-ntbuild
           path: $GITHUB_WORKSPACE/cowserve.exe
